In [141]:
import numpy as np
import matplotlib.pyplot as plt
import mpl_toolkits.mplot3d as m3d
import vtk
from vtk.util.numpy_support import vtk_to_numpy, numpy_to_vtk

# import redirc

%matplotlib inline

# @redirc.print_stdout_stderr
def read_vtk_file(filename):
    # Open file and read unstructured grid.
    reader = vtk.vtkUnstructuredGridReader()
    reader.SetFileName(filename)
    reader.Update()
    grid = reader.GetOutput()
    
    # Read points.
    vtk_points = grid.GetPoints()
    xyz3d = vtk_to_numpy( vtk_points.GetData() )
    #print(grid)
    # Read cells.
    cells = vtk_to_numpy( grid.GetCells().GetData() )
    cell_locations = vtk_to_numpy( grid.GetCellLocationsArray() )
    cell_types = vtk_to_numpy( grid.GetCellTypesArray() )
    
    return xyz3d, cells, cell_locations, cell_types

filename = 'test.vtk'
xyz3d_, cells_, cell_locations_, cell_types_ = read_vtk_file(filename)

In [142]:
read_vtk_file(filename)  

(array([[  2.05609859,  -5.04685482,  -6.53584266],
        [  2.95249645, -11.        ,  -9.07161668],
        [  6.61867976,  -6.08596723, -10.13942747],
        ...,
        [  5.5       , -11.        , -14.2043    ],
        [-11.        ,   0.        ,   0.        ],
        [ -8.75      , -11.        ,   0.        ]]),
 array([  4,   0,   1, ..., 199,  33,  35]),
 array([   0,    4,    8, ..., 6224, 6228, 6232]),
 array([10, 10, 10, ..., 10, 10, 10], dtype=uint8))

In [143]:
np.shape(xyz3d_)

(488, 3)

In [144]:
np.shape(cell_types_)

(1559,)

In [145]:
    reader = vtk.vtkUnstructuredGridReader()
    reader.SetFileName(filename)
    reader.Update()
    grid = reader.GetOutput()
    
    # Read points.
    vtk_points = grid.GetPoints()
    xyz3d = vtk_to_numpy( vtk_points.GetData() )
    #print(grid)
    # Read cells.
    cells = vtk_to_numpy( grid.GetCells().GetData() )
    cell_locations = vtk_to_numpy( grid.GetCellLocationsArray() )
    cell_types = vtk_to_numpy( grid.GetCellTypesArray() )

In [146]:
c2p = vtk.vtkCellDataToPointData()
c2p.SetInputData(grid)
c2p.Update()
ptdata = c2p.GetOutput()

In [147]:
    vtk_points = ptdata.GetPoints()
    xyz3d = vtk_to_numpy( vtk_points.GetData() )

In [148]:
np.shape(xyz3d)

(488, 3)

In [149]:
ptdata

<vtkmodules.vtkCommonDataModel.vtkUnstructuredGrid(0x7f9e5ff68d80) at 0x172e27340>

In [150]:
import vtk
import csv

fileIn  = 'myPoints.vtk'
fileOut  = 'myTable.csv'

# reader = vtk.vtkGenericDataObjectReader()
# reader.SetFileName(fileIn)
# reader.Update()

#point_obj = reader.GetOutput()

point_obj = ptdata
points = [(point_obj.GetPoint(i)[0], point_obj.GetPoint(i)[1], point_obj.GetPoint(i)[2], 0) for i in range(int(point_obj.GetNumberOfPoints()))]
with open(fileOut, 'w') as csvfileout:
    writer = csv.writer(csvfileout)
    writer.writerows(points)
    

In [151]:
point_obj = ptdata.GetAttributesAsFieldData(0)
cells = vtk_to_numpy( ptdata.GetCells().GetData() )

In [152]:
xyz3d, cells, cell_locations, cell_types

(array([[  2.05609859,  -5.04685482,  -6.53584266],
        [  2.95249645, -11.        ,  -9.07161668],
        [  6.61867976,  -6.08596723, -10.13942747],
        ...,
        [  5.5       , -11.        , -14.2043    ],
        [-11.        ,   0.        ,   0.        ],
        [ -8.75      , -11.        ,   0.        ]]),
 array([  4,   0,   1, ..., 199,  33,  35]),
 array([   0,    4,    8, ..., 6224, 6228, 6232]),
 array([10, 10, 10, ..., 10, 10, 10], dtype=uint8))

In [153]:
print(ptdata.GetPointData().GetArray(3))

None


In [154]:
print(vtk_to_numpy(ptdata.GetData(0)))
print(vtk_to_numpy(ptdata.GetPointData().GetScalars()))

TypeError: arguments do not match any overloaded methods

In [155]:
import vtk
import csv

fileIn  = 'test.vtk'
fileOut  = 'myTable2.csv'

reader = vtk.vtkGenericDataObjectReader()
reader.SetFileName(fileIn)
reader.Update()

point_obj = reader.GetOutput()
points = point_obj.GetPoints()

table = vtk.vtkDataObjectToTable()
table.SetInputData(point_obj)
table.Update()
table.GetOutput().AddColumn(points.GetData())
table.Update()

writer = vtk.vtkDelimitedTextWriter()
writer.SetInputConnection(table.GetOutputPort())
writer.SetFileName(fileOut)
writer.Update()
writer.Write()

#print(point_obj)
# https://discourse.vtk.org/t/save-polydata-to-csv-using-vtkdelimitedtextwriter/986/4

1

In [156]:
print(array1)

In [157]:
# vec1 = usg.GetPointData().GetVector('vector1')

In [158]:
import pyvista as pv

In [159]:
data = pv.read('test.vtk')
print(data)

print(data.point_arrays.keys())

UnstructuredGrid (0x17309cfa0)
  N Cells:	1559
  N Points:	488
  X Bounds:	-1.100e+01, 1.100e+01
  Y Bounds:	-1.100e+01, 1.100e+01
  Z Bounds:	-1.420e+01, 0.000e+00
  N Arrays:	5

dict_keys([])


In [160]:
data["name of array"]

In [161]:
import vtk
from vtk.numpy_interface import dataset_adapter as dsa

reader = vtk.vtkUnstructuredGridReader()
reader.SetFileName('test.vtk')
reader.ReadAllScalarsOn()
reader.ReadAllVectorsOn()
reader.Update()

adapter = dsa.WrapDataObject(reader.GetOutput())
print(adapter.PointData.keys()) # ['hu', 'disp']
print(adapter.CellData.keys())  # []
print(adapter.FieldData.keys()) # []

[]
['Resistivity(log10)', 'Resistivity/Ohmm', '_Attribute', '_Marker', 'coverage(log10)']
[]


In [166]:
# # Determine the name of each field and place it in an array.
# number_of_fields = reader.GetOutput().GetPointData().GetNumberOfArrays()

# field_names = []
# for i in range(number_of_fields):
#     field_names.append(reader.GetOutput().GetPointData().GetArrayName(i))
# print(field_names, number_of_fields)
# # Determine the index of the field strain_rate
# idx = field_names.index("Resistivity/Ohmm")

# # Example: Extract values of strain_rate
# field_vtk_array = reader.GetOutput().GetPointData().GetArray(idx)
import vtk
from vtk.numpy_interface import dataset_adapter as dsa

reader = vtk.vtkUnstructuredGridReader()
reader.SetFileName('test.vtk')
reader.ReadAllScalarsOn()
reader.ReadAllVectorsOn()
reader.Update()
# strain_rate = numpy_support.vtk_to_numpy(field_vtk_array)

In [191]:



converter = vtk.vtkCellDataToPointData()
converter.ProcessAllArraysOn()
converter.SetInputConnection(reader.GetOutputPort())
converter.Update()

keys = adapter.CellData.keys()
print(keys[0])
vtk_to_numpy(converter.GetOutput().GetPointData().GetArray(keys[4]))
arr = [vtk_to_numpy(converter.GetOutput().GetPointData().GetArray(keys[0])) for i in range(len(keys))]

# print(converter.GetOutput())
# print(arr)

Resistivity(log10)


In [218]:
import vtk
import csv

fileIn  = 'test.vtk'
fileOut  = 'myTable.csv'

reader = vtk.vtkUnstructuredGridReader()
reader.SetFileName('test.vtk')
reader.ReadAllScalarsOn()
reader.ReadAllVectorsOn()
reader.Update()

point_obj = reader.GetOutput()

point_obj = ptdata
converter = vtk.vtkCellDataToPointData()
converter.ProcessAllArraysOn()
converter.SetInputConnection(reader.GetOutputPort())
converter.Update()
arr = vtk_to_numpy(converter.GetOutput().GetPointData().GetArray('Resistivity/Ohmm'))

# keys = adapter.CellData.keys()
# arr = [vtk_to_numpy(converter.GetOutput().GetPointData().GetArray(keys[0])) for i in range(len(keys))]
# nparray = np.array(arr).transpose()

points = [(point_obj.GetPoint(i)[0], point_obj.GetPoint(i)[1], point_obj.GetPoint(i)[2], arr[i]) for i in range(int(point_obj.GetNumberOfPoints()))]
with open(fileOut, 'w') as csvfileout:
    writer = csv.writer(csvfileout)
    writer.writerow(["x", "y", "z", "Resistivity/Ohmm"])
    writer.writerows(points)

In [176]:
print(point_obj.GetPoint(0))

(2.056098588435, -5.046854818664, -6.535842662675)


In [195]:
nparray = np.array(arr).transpose()

In [196]:
np.shape(nparray)

(488, 5)

In [197]:
nparray

array([[0.94196955, 0.94196955, 0.94196955, 0.94196955, 0.94196955],
       [1.0182403 , 1.0182403 , 1.0182403 , 1.0182403 , 1.0182403 ],
       [1.11077467, 1.11077467, 1.11077467, 1.11077467, 1.11077467],
       ...,
       [1.1231997 , 1.1231997 , 1.1231997 , 1.1231997 , 1.1231997 ],
       [0.62275706, 0.62275706, 0.62275706, 0.62275706, 0.62275706],
       [0.90278333, 0.90278333, 0.90278333, 0.90278333, 0.90278333]])

In [198]:
nparray[0]

array([0.94196955, 0.94196955, 0.94196955, 0.94196955, 0.94196955])

In [200]:
keys = converter.CellData.keys()

AttributeError: 'vtkmodules.vtkFiltersCore.vtkCellDataToPointData' object has no attribute 'CellData'

In [206]:
import pandas as pd
df = pd.DataFrame(points)
df.columns = ["x", "y", "z", "Resistivity/Ohmm"]
df

x          y          z  Resistivity/Ohmm
0     2.056099  -5.046855  -6.535843          9.152093
1     2.952496 -11.000000  -9.071617         10.561621
2     6.618680  -6.085967 -10.139427         12.977863
3     5.921467  -8.562813  -6.579852          9.178093
4    -6.589772   8.817694  -5.032836          8.523189
..         ...        ...        ...               ...
483  11.000000  11.000000  -8.352150         11.808890
484   5.500000  11.000000 -14.204300         13.721167
485   5.500000 -11.000000 -14.204300         13.290502
486 -11.000000   0.000000   0.000000          4.196800
487  -8.750000 -11.000000   0.000000          8.005138

[488 rows x 4 columns]

In [214]:
# Set markers for each point. Hard Code for now, but figure out a way to do this from rho.map
rho_map = [5, 100]
layer = -5
marker = []
for i in range(len(points)):
    if points[i][2] < layer:
        marker.append(rho_map[1])
    elif points[i][2]>=layer:
        marker.append(rho_map[0])
    else:
        print("something's wrong getting markers for csv")
        marker.append('nan')

In [215]:
points = [(point_obj.GetPoint(i)[0], point_obj.GetPoint(i)[1], point_obj.GetPoint(i)[2], arr[i], marker[i]) for i in range(int(point_obj.GetNumberOfPoints()))]

In [216]:
df = pd.DataFrame(points)
df.columns = ["x", "y", "z", "Resistivity/Ohmm", "Marker"]
df

x          y          z  Resistivity/Ohmm  Marker
0     2.056099  -5.046855  -6.535843          9.152093     100
1     2.952496 -11.000000  -9.071617         10.561621     100
2     6.618680  -6.085967 -10.139427         12.977863     100
3     5.921467  -8.562813  -6.579852          9.178093     100
4    -6.589772   8.817694  -5.032836          8.523189     100
..         ...        ...        ...               ...     ...
483  11.000000  11.000000  -8.352150         11.808890     100
484   5.500000  11.000000 -14.204300         13.721167     100
485   5.500000 -11.000000 -14.204300         13.290502     100
486 -11.000000   0.000000   0.000000          4.196800       5
487  -8.750000 -11.000000   0.000000          8.005138       5

[488 rows x 5 columns]

In [221]:
df.to_csv("test.csv", index=False)

In [14]:
import vtk
import csv
from vtk.util.numpy_support import vtk_to_numpy, numpy_to_vtk
import numpy as np
import pandas as pd
# import sys


# inFile = sys.argv[1]
# outFile = sys.argv[2]

fileIn  = 'test.vtk'
fileOut  = 'output.csv'

reader = vtk.vtkUnstructuredGridReader()
reader.SetFileName('test.vtk')
reader.ReadAllScalarsOn()
reader.ReadAllVectorsOn()
reader.Update()

point_obj = reader.GetOutput()

#point_obj = ptdata
converter = vtk.vtkCellDataToPointData()
converter.ProcessAllArraysOn()
converter.SetInputConnection(reader.GetOutputPort())
converter.Update()
arr = vtk_to_numpy(converter.GetOutput().GetPointData().GetArray('Resistivity/Ohmm'))

points = np.array([(point_obj.GetPoint(i)[0], point_obj.GetPoint(i)[1], point_obj.GetPoint(i)[2], arr[i]) for i in range(int(point_obj.GetNumberOfPoints()))])

# Set markers for each point. Hard Code for now, but figure out a way to do this from rho.map
rho_map = [5, 100]
layer = -5
marker = []
for i in range(len(points)):
    if points[i][2] < layer:
        marker.append(rho_map[1])
    elif points[i][2]>=layer:
        marker.append(rho_map[0])
    else:
        print("something's wrong getting markers for csv")
        marker.append('nan')

marker = np.reshape(np.array(marker), (len(marker), 1))
markered_points = np.concatenate((points, marker), 1)

df = pd.DataFrame(markered_points)
df.columns = ["x", "y", "z", "Resistivity/Ohmm", "Marker"]

df.to_csv("test.csv", index=False)