In [1]:
import numpy as np
import matplotlib.pyplot as plt
import mpl_toolkits.mplot3d as m3d
import vtk
from vtk.util.numpy_support import vtk_to_numpy, numpy_to_vtk

# import redirc

%matplotlib inline

# @redirc.print_stdout_stderr
def read_vtk_file(filename):
    # Open file and read unstructured grid.
    reader = vtk.vtkUnstructuredGridReader()
    reader.SetFileName(filename)
    reader.Update()
    grid = reader.GetOutput()
    
    # Read points.
    vtk_points = grid.GetPoints()
    xyz3d = vtk_to_numpy( vtk_points.GetData() )
    #print(grid)
    # Read cells.
    cells = vtk_to_numpy( grid.GetCells().GetData() )
    cell_locations = vtk_to_numpy( grid.GetCellLocationsArray() )
    cell_types = vtk_to_numpy( grid.GetCellTypesArray() )
    
    return xyz3d, cells, cell_locations, cell_types

filename = 'test.vtk'
xyz3d_, cells_, cell_locations_, cell_types_ = read_vtk_file(filename)

In [2]:
read_vtk_file(filename)  

(array([[  2.05609859,  -5.04685482,  -6.53584266],
        [  2.95249645, -11.        ,  -9.07161668],
        [  6.61867976,  -6.08596723, -10.13942747],
        ...,
        [  5.5       , -11.        , -14.2043    ],
        [-11.        ,   0.        ,   0.        ],
        [ -8.75      , -11.        ,   0.        ]]),
 array([  4,   0,   1, ..., 199,  33,  35]),
 array([   0,    4,    8, ..., 6224, 6228, 6232]),
 array([10, 10, 10, ..., 10, 10, 10], dtype=uint8))

In [3]:
np.shape(xyz3d_)

(488, 3)

In [4]:
np.shape(cell_types_)

(1559,)

In [5]:
    reader = vtk.vtkUnstructuredGridReader()
    reader.SetFileName(filename)
    reader.Update()
    grid = reader.GetOutput()
    
    # Read points.
    vtk_points = grid.GetPoints()
    xyz3d = vtk_to_numpy( vtk_points.GetData() )
    #print(grid)
    # Read cells.
    cells = vtk_to_numpy( grid.GetCells().GetData() )
    cell_locations = vtk_to_numpy( grid.GetCellLocationsArray() )
    cell_types = vtk_to_numpy( grid.GetCellTypesArray() )

In [6]:
c2p = vtk.vtkCellDataToPointData()
c2p.SetInputData(grid)
c2p.Update()
ptdata = c2p.GetOutput()

In [7]:
    vtk_points = ptdata.GetPoints()
    xyz3d = vtk_to_numpy( vtk_points.GetData() )

In [8]:
np.shape(xyz3d)

(488, 3)

In [9]:
ptdata

<vtkmodules.vtkCommonDataModel.vtkUnstructuredGrid(0x7f9e63a78d80) at 0x10f844820>

In [10]:
import vtk
import csv

fileIn  = 'myPoints.vtk'
fileOut  = 'myTable.csv'

# reader = vtk.vtkGenericDataObjectReader()
# reader.SetFileName(fileIn)
# reader.Update()

#point_obj = reader.GetOutput()

point_obj = ptdata
points = [(point_obj.GetPoint(i)[0], point_obj.GetPoint(i)[1], point_obj.GetPoint(i)[2], 0) for i in range(int(point_obj.GetNumberOfPoints()))]
with open(fileOut, 'w') as csvfileout:
    writer = csv.writer(csvfileout)
    writer.writerows(points)
    

In [11]:
point_obj = ptdata.GetAttributesAsFieldData(0)
points

[(2.056098588435, -5.046854818664, -6.535842662675, 0),
 (2.952496453214, -11.0, -9.071616679161, 0),
 (6.618679758214, -6.085967230734, -10.139427474564, 0),
 (5.921466559117, -8.56281341256, -6.579852406563, 0),
 (-6.589772086175, 8.817693974959, -5.032836255414, 0),
 (-7.456424766767, 11.0, -8.531530613648, 0),
 (-8.269125497403, 7.677180691964, -8.800106381944, 0),
 (-9.373513980084, 11.0, -6.50998018986, 0),
 (11.0, -9.623359386581, -1.065371683303, 0),
 (9.204392252705, -8.264335040134, 0.0, 0),
 (11.0, -8.75, 0.0, 0),
 (11.0, -8.417487255696, -1.441524244981, 0),
 (10.0, 10.0, 0.0, 0),
 (10.0, 10.0, -2.5, 0),
 (8.954208646248, 11.0, -1.212187388043, 0),
 (11.0, 9.523198680788, -1.115828158078, 0),
 (10.0, 0.0, 0.0, 0),
 (11.0, 0.0, 0.0, 0),
 (11.0, -1.25, 0.0, 0),
 (11.0, -0.575379592621, -1.429520530143, 0),
 (11.0, 0.0, -14.2043, 0),
 (11.0, 2.750048726052, -9.500318484382, 0),
 (7.464567985486, 0.051704139931, -7.835158067459, 0),
 (11.0, -1.47686794996, -10.09281414796, 0),
